// Generated by Wrangler on Wed Nov 27 2024 00:04:46 GMT-0500 (Eastern Standard Time)
// by running `wrangler types`

interface Env {
	STRIPE_SECRET_KEY: string;
	STRIPE_PUBLIC_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
}
