name = "nocturnclothing"
compatibility_date = "2024-01-01"
pages_build_output_dir = "build/client"

[vars]
STRIPE_PUBLIC_KEY = ""
STRIPE_SECRET_KEY = ""
STRIPE_WEBHOOK_SECRET = ""

# Add bindings section
[env.production]
[env.production.vars]
